# Site settings
title: Dongyupu's Blog
header-img: img/home-bg.jpg
email: dongyupu@foxmail.com
description: "Dream big, work smart, deliver fast!Software to plan, collaborate, code, and service. Built for teams."
baseurl: "/test"
url: "http://dongyupu.github.io/test"
twitter_username: 741375879
github_username:  dongyupu
facebook_username:  dong.yupu.7

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
