# Site settings
title: Colorful City 
         <br>西美·花街
header-img: img/home-bg-0.jpg
email: dongyupu@foxmail.com
description: "去哪里逛？
          遇见花街，爱上花街。"
baseurl: "/colorfulcity"
url: "http://dongyupu.github.io/colorfulcity"
twitter_username: 741375879
github_username:  dongyupu
facebook_username:  dong.yupu.7
weibo_username: dongyupu1988
#zhihu_username: dongyupy

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
