# Site settings
title: Clean Blog
header-img: img/home-bg.jpg
email: dongyupu@foxmail.com
description: "Write your site description here. It will be used as your sites meta description as well!"
baseurl: "/test"
url: "http://dongyupu.github.io/test"
twitter_username: 741375879
github_username:  dongyupu
facebook_username:  dong.yupu.7

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
