# Site settings
title: <h2>Colorful City · 花街</h2>
header-img: img/home-bg-3.jpg
email: dongyupu@foxmail.com
description: "去哪里逛？
          遇见花街，爱上花街。"
baseurl: "/test"
url: "http://dongyupu.github.io/test"
twitter_username: 741375879
github_username:  dongyupu
facebook_username:  dong.yupu.7
weibo_username: dongyupu1988
#zhihu_username: dongyupy

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
